const defaults=[
{id:1,g:"w",name:"CALZA LP CORE",price:39900,color:"Negro",tag:"NUEVO",img:"https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=800&q=85"},
{id:2,g:"w",name:"TOP LP MOTION",price:28900,color:"Negro",tag:"BEST SELLER",img:"https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=85"},
{id:3,g:"w",name:"BIKER LP FLEX",price:32900,color:"Grafito",tag:"DROP 01",img:"https://images.unsplash.com/photo-1594381898411-846e7d193883?auto=format&fit=crop&w=800&q=85"},
{id:4,g:"w",name:"REMERA LP OVERSIZE",price:34900,color:"Blanco",tag:"NUEVO",img:"https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=85"},
{id:5,g:"m",name:"REMERA LP PERFORMANCE",price:35900,color:"Negro",tag:"NUEVO",img:"https://images.unsplash.com/photo-1581009137042-c552e485697a?auto=format&fit=crop&w=800&q=85"},
{id:6,g:"m",name:"SHORT LP TRAINING",price:31900,color:"Negro",tag:"BEST SELLER",img:"https://images.unsplash.com/photo-1584466977773-e625c37cdd50?auto=format&fit=crop&w=800&q=85"},
{id:7,g:"m",name:"MUSCULOSA LP AIR",price:28900,color:"Blanco",tag:"DROP 01",img:"https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=800&q=85"},
{id:8,g:"m",name:"JOGGER LP MOVE",price:46900,color:"Grafito",tag:"NUEVO",img:"https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=800&q=85"}];
let products=JSON.parse(localStorage.getItem("lp_products")||"null")||defaults,cart=JSON.parse(localStorage.getItem("lp_cart")||"[]");
const money=n=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(n);
function draw(){["w","m"].forEach(g=>{document.getElementById(g==="w"?"women":"men").innerHTML=products.filter(p=>p.g===g).map(p=>'<article class="product"><div class="productImg" style="background-image:url('+p.img+')"><span class="tag">'+(p.tag||"LP SPORT")+'</span><button class="quick" onclick="add('+p.id+')">AGREGAR A LA BOLSA +</button></div><div class="info"><div><h3>'+p.name+'</h3><p>'+p.color+' · S / M / L / XL</p></div><b>'+money(p.price)+'</b></div></article>').join("")})}
function add(id){let p=products.find(x=>x.id===id);cart.push({...p,cid:Date.now(),size:"M"});save();openCart()}function gift(){cart.push({id:999,name:"LP SPORT GIFT CARD",price:50000,color:"Digital",img:"https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=500&q=80",cid:Date.now(),size:"—"});save();openCart()}
function save(){localStorage.setItem("lp_cart",JSON.stringify(cart));drawCart()}function drawCart(){count.textContent=cart.length;items.innerHTML=cart.length?cart.map(x=>'<div class="line"><img src="'+x.img+'"><div><h4>'+x.name+'</h4><small>TALLE '+x.size+' · '+x.color+'</small><br><button onclick="remove('+x.cid+')" style="border:0;background:none;text-decoration:underline;font-size:9px">ELIMINAR</button></div><b>'+money(x.price)+'</b></div>').join(""):"<p>Tu bolsa está vacía.</p>";subtotal.textContent=money(cart.reduce((a,x)=>a+x.price,0))}
function remove(id){cart=cart.filter(x=>x.cid!==id);save()}function openCart(){document.getElementById("cart").classList.add("open")}function closeCart(){document.getElementById("cart").classList.remove("open")}function closeModal(){modal.classList.remove("show")}
function checkout(){if(!cart.length)return alert("Tu bolsa está vacía");closeCart();modal.classList.add("show");modalBody.innerHTML='<small>CHECKOUT SEGURO</small><h2>FINALIZÁ TU COMPRA</h2><form id="checkout"><div class="form"><input name="name" placeholder="Nombre y apellido" required><input type="email" name="email" placeholder="Email" required><input name="phone" placeholder="Teléfono" required><input name="province" placeholder="Provincia" required><input class="full" name="address" placeholder="Dirección de entrega" required></div><h4>ENVÍO</h4><label class="choice"><input type="radio" name="ship" value="Correo a domicilio" checked> Correo a domicilio · seguimiento online</label><h4>MEDIO DE PAGO</h4><label class="choice"><input type="radio" name="pay" value="Mercado Pago" checked> Mercado Pago / Tarjetas</label><label class="choice"><input type="radio" name="pay" value="Transferencia"> Transferencia bancaria</label><p><b>TOTAL: '+money(cart.reduce((a,x)=>a+x.price,0))+'</b></p><button class="pay" type="submit">CONFIRMAR PEDIDO →</button><p style="font-size:10px;color:#777">Demo funcional. El cobro real se activa al conectar las credenciales comerciales.</p></form>';document.getElementById("checkout").onsubmit=order}
function order(e){e.preventDefault();let f=new FormData(e.target),code="LP-"+Math.floor(100000+Math.random()*900000),orders=JSON.parse(localStorage.getItem("lp_orders")||"[]");orders.unshift({code,date:new Date().toLocaleString("es-AR"),customer:f.get("name"),email:f.get("email"),phone:f.get("phone"),address:f.get("address")+", "+f.get("province"),pay:f.get("pay"),status:"Pedido confirmado",items:[...cart],total:cart.reduce((a,x)=>a+x.price,0)});localStorage.setItem("lp_orders",JSON.stringify(orders));cart=[];save();modalBody.innerHTML='<small>¡GRACIAS!</small><h2>PEDIDO CONFIRMADO</h2><p>Tu número de seguimiento:</p><h2 style="background:#d8ff00;padding:15px;display:inline-block">'+code+'</h2><p>Guardalo para consultar el estado de tu compra.</p>'}
function openTrack(){modal.classList.add("show");modalBody.innerHTML='<small>SEGUIMIENTO LP SPORT</small><h2>¿DÓNDE ESTÁ TU PEDIDO?</h2><p>Ingresá tu número de orden.</p><div class="track"><input id="trackCode" placeholder="LP-000000"><button onclick="track()">BUSCAR</button></div><div id="result"></div>'}
function track(){let code=trackCode.value.trim().toUpperCase(),orders=JSON.parse(localStorage.getItem("lp_orders")||"[]"),o=orders.find(x=>x.code===code);result.innerHTML=o?'<div class="status"><b>'+o.code+'</b><h3>'+o.status+'</h3><p>'+o.address+'</p></div>':'<div class="status">No encontramos ese pedido.</div>'}
draw();drawCart();